
--ÄíÆùÇÔ
CREATE TABLE COUPON_TABLE(
    COUPON_TABLE_NO NUMBER PRIMARY KEY,
    CUSTOMER_ID VARCHAR2(30) REFERENCES CUSTOMER(CUSTOMER_ID)  ON                        
                                                  DELETE CASCADE
);

--ÄíÆù
CREATE TABLE COUPON(
    COUPON_NO NUMBER PRIMARY KEY,
    COUPON_TABLE_NO NUMBER REFERENCES
    COUPON_TABLE(COUPON_TABLE_NO)
    ON DELETE CASCADE,
    SALE_PERCENT NUMBER,
    USED VARCHAR2(5) DEFAULT 'FALSE'
);


