
--ÄíÆùÇÔ
CREATE TABLE COUPON_TABLE(
    COUPON_TABLE_NO NUMBER PRIMARY KEY,
    CUSTOMER_ID VARCHAR2(30) REFERENCES CUSTOMER(CUSTOMER_ID)  ON                        
                                                  DELETE CASCADE
);

--ÄíÆù
CREATE TABLE COUPON(
    COUPON_NO NUMBER PRIMARY KEY,
    COUPON_TABLE_NO NUMBER REFERENCES
    COUPON_TABLE(COUPON_TABLE_NO)
    ON DELETE CASCADE,
    SALE_PERCENT NUMBER,
    USED VARCHAR2(5) DEFAULT 'FALSE'
);

--ÄíÆùÇÔ »ý¼º
INSERT INTO COUPON_TABLE(COUPON_TABLE_NO, CUSTOMER_ID) VALUES(COUPON_TABLE_NO_SEQ.NEXTVAL , 'CHOI1');

--ÄíÆù »ý¼º
INSERT INTO COUPON(COUPON_NO, COUPON_TABLE_NO, SALE_PERCENT) VALUES(COUPON_COUPON_NO_SEQ.NEXTVAL, COUPON_TABLE_NO_SEQ.CURRENTVAL, 10);
INSERT INTO COUPON(COUPON_NO, COUPON_TABLE_NO, SALE_PERCENT) VALUES(COUPON_COUPON_NO_SEQ.NEXTVAL, COUPON_TABLE_NO_SEQ.CURRENTVAL, 20);
INSERT INTO COUPON(COUPON_NO, COUPON_TABLE_NO, SALE_PERCENT) VALUES(COUPON_COUPON_NO_SEQ.NEXTVAL, COUPON_TABLE_NO_SEQ.CURRENTVAL, 30);
