CREATE TABLE COUPON_TABLE(
    COUPON_TABLE_NO VARCHAR2 PRIMARY KEY,
    CUSTOMER_ID VARCHAR2(30) REFERENCES CUSTOMER(CUSTOMER_ID)  ON DELETE CASCADE
)

CREATE TABLE COUPON(
    COUPON_NO VARCHAR2 PRIMARY KEY,
    COUPON_TABLE_NO VARCHAR2 REFERENCES COUPON_TABLE(COUPON_TABLE_NO) ON DELETE CASCADE,
    SALE_PERCENT NUMBER,
    USED VARCHAR2(5) DEFAULT 'FALSE'
)