CREATE TABLE CUSTOMER (
	CUSTOMER_ID VARCHAR2(30) PRIMARY KEY,
	PWD VARCHAR2(30) NOT NULL,
	CUSTOMER_NAME VARCHAR2(12) NOT NULL,
	BIRTH NUMBER(8) NOT NULL,
	EMAIL VARCHAR2(30),
	ADDR VARCHAR2(50),
	CONTACT VARCHAR2(15),
	SIGN_DATE DATE DEFAULT SYSDATE
);

