
CREATE TABLE LIQUOR_TABLE(
LIQUOR_TABLE_NO NUMBER PRIMARY KEY,
LIQUOR_TYPE VARCHAR2(9) NOT NULL,
ORIGIN VARCHAR2(10)
);

--양주 테이블 생성 
CREATE TABLE LIQUOR(
	LIQUOR_NO NUMBER PRIMARY KEY,
	LIQUOR_TABLE_NO NUMBER REFERENCES LIQUOR_TABLE(LIQUOR_TABLE_NO),
	LIQUOR_NAME VARCHAR2(30) NOT NULL UNIQUE,
	LIQUOR_PRICE NUMBER(10),
	STOCK NUMBER(3) DEFAULT 20,
	ADD_DATE DATE
);


CREATE SEQUENCE LIQUOR_TABLE_NO;  -- 양주 테이블의 번호 
CREATE SEQUENCE LIQUOR_NO;  --양주 하나하나의 번호 

INSERT INTO LIQUOR_TABLE VALUES(LIQUOR_TABLE_NO.NEXTVAL, '위스키', '스페인');

SELECT * FROM LIQUOR_TABLE;

INSERT INTO LIQUOR VALUES(LIQUOR_NO.NEXTVAL, 1,  '발렌타인 700ml', 109000, 20, '2021-08-26' );
INSERT INTO LIQUOR VALUES(LIQUOR_NO.NEXTVAL, 1,  '잭 다니엘 1000ml', 49000, 20, '2021-08-26' );
INSERT INTO LIQUOR VALUES(LIQUOR_NO.NEXTVAL, 1,  '제임슨 200ml', 14000, 20, '2021-08-26' );

SELECT * FROM LIQUOR;
