
CREATE TABLE LIQUOR_TABLE(
LIQUOR_TABLE_NO NUMBER PRIMARY KEY,
LIQUOR_TYPE VARCHAR2(9) NOT NULL,
ORIGIN VARCHAR2(10)
);

--양주 테이블 생성 
CREATE TABLE LIQUOR(
	LIQUOR_NO NUMBER PRIMARY KEY,
	LIQUOR_TABLE_NO NUMBER REFERENCES LIQUOR_TABLE(LIQUOR_TABLE_NO),
	LIQUOR_NAME VARCHAR2(30) NOT NULL UNIQUE,
	LIQUOR_PRICE NUMBER(10),
	STOCK NUMBER(3) DEFAULT 20,
	ADD_DATE DATE
);

