--주문 테이블 생성
CREATE TABLE ORDERS(
	ORDER_NO NUMBER(10) PRIMARY KEY,
	CUSTOMER_ID VARCHAR2(30) REFERENCES CUSTOMER(CUSTOMER_ID),
	ORDER_DATE DATE NOT NULL,
	ORDER_ADDR VARCHAR2(100) NOT NULL, 
	ORDER_STATUS VARCHAR2(20) DEFAULT '결제확인중', 
	FINAL_PRICE	NUMBER
);


--주문 테이블용 시퀀스 생성
CREATE SEQUENCE ORDER_NO_SEQ NOCACHE;


--주문상세 테이블 생성
CREATE TABLE ORDER_DETAIL(
	ORDER_DETAIL_NO NUMBER PRIMARY KEY,
	LIQUOR_NO NUMBER REFERENCES LIQUOR(LIQUOR_NO),
	ORDER_NO NUMBER(10) REFERENCES ORDERS(ORDER_NO),
	COUNT NUMBER DEFAULT 1, 
	ORDER_PRICE NUMBER(10) 
);

--주문상세 테이블용 시퀀스 생성
CREATE SEQUENCE ORDER_DETAIL_SEQ NOCACHE;

