--주문 테이블 생성
CREATE TABLE ORDERS(
	ORDER_NO NUMBER(10) PRIMARY KEY,
	CUSTOMER_ID VARCHAR2(30) REFERENCES CUSTOMER(CUSTOMER_ID),
	ORDER_DATE DATE NOT NULL,
	ORDER_ADDR VARCHAR2(100) NOT NULL, 
	ORDER_STATUS VARCHAR2(20) DEFAULT '결제확인중', 
	FINAL_PRICE	NUMBER
);


--주문 테이블용 시퀀스 생성
CREATE SEQUENCE ORDER_NO_SEQ NOCACHE;


--주문상세 테이블 생성
CREATE TABLE ORDER_DETAIL(
	ORDER_DETAIL_NO NUMBER PRIMARY KEY,
	LIQUOR_NO NUMBER REFERENCES LIQUOR(LIQUOR_NO),
	ORDER_NO NUMBER(10) REFERENCES ORDERS(ORDER_NO),
	COUNT NUMBER DEFAULT 1, 
	ORDER_PRICE NUMBER(10) 
);

--주문상세 테이블용 시퀀스 생성
CREATE SEQUENCE ORDER_DETAIL_SEQ NOCACHE;


--주문 생성
INSERT INTO ORDERS
(ORDER_NO, ORDER_DATE, ORDER_ADDR, ORDER_STATUS, FINAL_PRICE, CUSTOMER_ID) 
VALUES(ORDER_NO_SEQ.NEXTVAL, SYSDATE, ?, ?, ?, ?);

--EX) ORDER_STATUS 를 일부러 안넣음(안넣으면 DEFAULT값 ‘결제확인중’들어갈테니까..
INSERT INTO ORDERS
(ORDER_NO, ORDER_DATE, ORDER_ADDR, FINAL_PRICE, CUSTOMER_ID) 
VALUES(ORDER_NO_SEQ.NEXTVAL, SYSDATE, '서울시 강동구', 0, 'CHOI1'); 

INSERT INTO ORDERS
(ORDER_NO, ORDER_DATE, ORDER_ADDR, FINAL_PRICE, CUSTOMER_ID) 
VALUES(ORDER_NO_SEQ.NEXTVAL, SYSDATE, '서울시 강동구', 0, 'YOO'); 

INSERT INTO ORDERS
(ORDER_NO, ORDER_DATE, ORDER_ADDR, FINAL_PRICE, CUSTOMER_ID) 
VALUES(ORDER_NO_SEQ.NEXTVAL, SYSDATE, '서울시 송파구', 0, 'KIM'); 
                                                                 
SELECT * FROM ORDERS

--주문 상세 생성
INSERT INTO ORDER_DETAIL
(ORDER_DETAIL_NO, LIQOUR_NO, ORDER_NO, COUNT, ORDER_PRICE)
VALUES(ORDER_DETAIL_NO_SEQ.NEXTVAL, ?, ?, ?, ?);

--EX)
INSERT INTO ORDER_DETAIL
(ORDER_DETAIL_NO, LIQUOR_NO, ORDER_NO, COUNT, ORDER_PRICE)
VALUES(ORDER_DETAIL_SEQ.NEXTVAL, 1, 1, 2, 0);

INSERT INTO ORDER_DETAIL
       (ORDER_DETAIL_NO,       LIQUOR_NO, ORDER_NO,            COUNT, ORDER_PRICE)
VALUES(ORDER_DETAIL_SEQ.NEXTVAL,   2,     ORDER_NO_SEQ.CURRVAL,  2,      0);

INSERT INTO ORDER_DETAIL
(ORDER_DETAIL_NO, LIQUOR_NO, ORDER_NO, COUNT, ORDER_PRICE)
VALUES(ORDER_DETAIL_SEQ.NEXTVAL, 3, 3, 2, 0);


SELECT * FROM ORDER_DETAIL

INSERT INTO ORDERS
(ORDER_NO, ORDER_DATE, ORDER_ADDR, FINAL_PRICE, CUSTOMER_ID) 
VALUES(ORDER_NO_SEQ.NEXTVAL, SYSDATE, '서울시 송파구', 0, 'KIM'); 

INSERT INTO ORDER_DETAIL
       (ORDER_DETAIL_NO,       LIQUOR_NO, ORDER_NO,            COUNT, ORDER_PRICE)
VALUES(ORDER_DETAIL_SEQ.NEXTVAL,   2,     ORDER_NO_SEQ.CURRVAL,  2,      0);

