--주문 테이블 생성
CREATE TABLE ORDER(
	ORDER_NO NUMBER(10) PRIMARY KEY,
	CUSTOMER_ID VARCHAR2(30) REFERENCES CUSTOMER(CUSTOMER_ID),
	ORDER_DATE DATE NOT NULL, /* 아마도 자바에서 SYSDATE로 넣어줄듯*/
	ORDER_ADDR VARCHAR2 NOT NULL, /*NULL 값 허용 안함*/
	ORDER_STATUS VARCHAR2 DEFAULT ‘결제확인중’, /*기본값=결제확인중*/
	FINAL_PRICE	 NUMBER
)

--주문 테이블용 시퀀스 생성
CREATE SEQUENCE ORDER_NO_SEQ NOCACHE;


--주문상세 테이블 생성
CREATE TABLE ORDER_DETAIL(
	ORDER_DETAIL_NO NUMBER PRIMARY KEY,
	LIQOUR_NO VARCHAR(10) REFERENCES LIQOUR(LIQOUR_NO),
	ORDER_NO NUMBER(10) REFERENCES ORDER(ORDER_NO),
	COUNT NUMBER DEFAULT 1, /*기본값 1*/
	ORDER_PRICE NUMBER(10) /*NUMBER 값 곱하기 LIQOUR_PRICE*/
);

--주문상세 테이블용 시퀀스 생성
CREATE SEQUENCE ORDER_DETAIL_SEQ NOCACHE;
