CREATE TABLE REVIEW(
REVIEW_NO VARCHAR2(10) PRIMARY KEY,
LIQUOR_NO NUMBER REFERENCES LIQUOR(LIQUOR_NO) ,
CUSTOMER_ID VARCHAR2(30) REFERENCES CUSTOMER(CUSTOMER_ID),
WRITE_DATE DATE,
CONTENT VARCHAR2(50)
); 

--장바구니 테이블 생성
CREATE TABLE CART (
	CART_NO NUMBER(10) PRIMARY KEY,
	CUSTOMER_ID VARCHAR2(30) REFERENCES CUSTOMER(CUSTOMER_ID),
	LIQUOR_NO NUMBER REFERENCES LIQUOR(LIQUOR_NO),
	CART_COUNT NUMBER
);

