CREATE TABLE REVIEW(
REVIEW_NO VARCHAR2(10) PRIMARY KEY,
LIQUOR_NO NUMBER REFERENCES LIQUOR(LIQUOR_NO) ,
CUSTOMER_ID VARCHAR2(30) REFERENCES CUSTOMER(CUSTOMER_ID),
WRITE_DATE DATE,
CONTENT VARCHAR2(50)
); 

SELECT * FROM REVIEW;

--REVIEW_NO 데이터타입 변경
ALTER TABLE REVIEW MODIFY REVIEW_NO NUMBER;

--리뷰 테이블 리뷰번호 REIVIEW_NO_SEQ 시퀀스 생성
CREATE SEQUENCE REVIEW_NO_SEQ  NOCACHE;


--장바구니 테이블 생성
CREATE TABLE CART (
	CART_NO NUMBER(10) PRIMARY KEY,
	CUSTOMER_ID VARCHAR2(30) REFERENCES CUSTOMER(CUSTOMER_ID),
	LIQUOR_NO NUMBER REFERENCES LIQUOR(LIQUOR_NO),
	CART_COUNT NUMBER
);

SELECT * FROM CART;

--장바구니번호 시퀀스 생성 CART_NO_SEQ
CREATE SEQUENCE CART_NO_SEQ NOCACHE;


